### ISSUE TITLE
Add vibration feature to the double-tap-to-wake (dt2w) implementation

### ISSUE THREAD

**Issue by vladimiroltean** [Quallenauge/Yoga-Tab-3-Plus-Issue-Tracker#13]
In fact this is mostly done. Keeping a placeholder until I have tested this well enough to be confident merging it. Code [here](https://github.com/vladimiroltean/android_kernel_lenovo_msm8976/tree/dt2w-vibration).

**Comment by Gabriel85** [comment]
Thanks, can you also implement a minimum time between the two taps of 125ms? :)
But I'm not sure if it is a good idea to vibrate by default, since I have never seen any official implementation who does that..

**Comment by vladimiroltean** [comment]
Really? All DT2W-enabled phones I had/saw had vibration too.

**Comment by Gabriel85** [comment]
At least none of my devices does that. I looked at several official kernel implementations and none had that feature. Probably something which should be implemented in userspace.
Also I can't see much sense in it, since you can hardly feel the vibration and the motor is loud and unpleasant. And what is the point of an haptic feedback of an haptic action? Especially since you can see with your eyes if it had turned on. And it won't do that by mistake in your pockets.. ;)

Furthermore the current implementation, isn't very good. It goes on, often by just grabbing the tablet (hope a minimum tap time helps with that), which is very annoying. Also it often takes more than 10 seconds before it actually wakes up and it uses relatively much battery power...

**Comment by vladimiroltean** [comment]
Released a build with said feature => closing.
